apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-dasn-ready-dasn-all
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: us-central1-docker.pkg.dev/infra-itaborai/registry-ita/spark-py-prod:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: gs://spark-ita/jobs/job_dasenda_ready_all_PA.py
  sparkVersion: "3.4.1"
  restartPolicy:
    type: Never
  
  driver:
    cores: 8
    memory: "30g"
    serviceAccount: spark-sa
    
    nodeSelector:
      spark-role: driver
    
    tolerations:
    - key: "spark-only"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    
    labels:
      version: 3.4.1
    
    env:
      - name: MUNICIPIO
        value: "5837"
      - name: BUCKET_NAME
        value: "k8s-dataita"

  executor:
    cores: 8
    instances: 5
    memory: "30g"
    serviceAccount: spark-sa
    
    nodeSelector:
      spark-role: executor
    
    tolerations:
    - key: "spark-only"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  sparkConf:
    "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "spark.hadoop.fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    "spark.hadoop.google.cloud.auth.service.account.enable": "true"
    "parentProject": "infra-itaborai"
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    "spark.databricks.delta.retentionDurationCheck.enabled": "true"
    "spark.databricks.delta.checkpointInterval": "10"
    "spark.delta.logLevel": "DEBUG"

  deps:
    jars:
      - local:///opt/spark/jars/spark-bigquery-with-dependencies_2.12-0.30.0.jar
      - local:///opt/spark/jars/delta-core_2.12-2.4.0.jar